### ISSUE TITLE
Test failures with Fiona v1.6.2

### ISSUE THREAD

**Issue by bekozi** [NCPP/ocgis#403]
who: @bekozi

Fiona added an element to their schema dictionary called "crs_wkt":

```
======================================================================
FAIL: test_csv_shapefile_conversion (ocgis.test.test_simple.test_simple.TestSimple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/ocgis/test/test_simple/test_simple.py", line 1218, in test_csv_shapefile_conversion
    [(u'UGID', 'int:10')])}})
AssertionError: The key "crs_wkt" was not found in the second dictionary.

======================================================================
FAIL: test_shp_conversion (ocgis.test.test_simple.test_simple.TestSimple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/ocgis/test/test_simple/test_simple.py", line 790, in test_shp_conversion
    'schema': {'geometry': 'Polygon', 'properties': schema_properties}})
  File "/opt/conda/lib/python2.7/site-packages/ocgis/test/base.py", line 103, in assertDictEqual
    raise AssertionError(msg)
AssertionError: The key "crs_wkt" was not found in the second dictionary.

======================================================================
FAIL: test_shp_conversion_with_external_geometries (ocgis.test.test_simple.test_simple.TestSimple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/ocgis/test/test_simple/test_simple.py", line 882, in test_shp_conversion_with_external_geometries
    'properties': properties}})
  File "/opt/conda/lib/python2.7/site-packages/ocgis/test/base.py", line 103, in assertDictEqual
    raise AssertionError(msg)
AssertionError: The key "crs_wkt" was not found in the second dictionary.
```

**Comment by bekozi** [comment]
Failures have disappeared with Fiona v1.6.3.
