### ISSUE TITLE
CentOS python3.6.8 test failure

### ISSUE THREAD

**Issue by basmac** [NCPP/ocgis#499]
Under CentOS
Linux linux256.psd.ad 2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 03:28:18 UTC 2018 x86_64 GNU/Linux
using gnu compilers 8.3, running the test I get the following - any problems ?
thanks

[root@linux256 ocgis]# export GDAL_DATA=$dir/anaconda3/share/gdal
[root@linux256 ocgis]# python -c "from ocgis.test import run_simple; run_simple(verbose=False)"
E..S...../usr/local/gfortran-8.3/anaconda3/lib/python3.6/site-packages/numpy/ma/core.py:3174: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  dout = self.data[indx]
/usr/local/gfortran-8.3/anaconda3/lib/python3.6/site-packages/numpy/ma/core.py:3206: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  mout = _mask[indx]
........................./usr/local/gfortran-8.3/anaconda3/lib/python3.6/site-packages/ocgis/conv/nc.py:181: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(type(val), int):
..../usr/local/gfortran-8.3/anaconda3/lib/python3.6/site-packages/ocgis/conv/nc.py:183: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif np.issubdtype(type(val), float):
................................S................
======================================================================
ERROR: Failure: ValueError (threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/gfortran-8.3/anaconda3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/local/gfortran-8.3/anaconda3/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/gfortran-8.3/anaconda3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/gfortran-8.3/anaconda3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/local/gfortran-8.3/anaconda3/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/local/gfortran-8.3/anaconda3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/gfortran-8.3/anaconda3/lib/python3.6/site-packages/ocgis/test/test_ocgis/test_contrib/test_library_icclim.py", line 25, in <module>
    from ocgis.contrib.library_icclim import IcclimTG, IcclimSU, AbstractIcclimFunction, IcclimDTR, IcclimETR, \
  File "/usr/local/gfortran-8.3/anaconda3/lib/python3.6/site-packages/ocgis/contrib/library_icclim.py", line 11, in <module>
    from icclim.calc_percentiles import get_percentile_dict, get_percentile_arr
  File "/usr/local/gfortran-8.3/anaconda3/lib/python3.6/site-packages/icclim/calc_percentiles.py", line 10, in <module>
    numpy.set_printoptions(threshold=numpy.nan)
  File "/usr/local/gfortran-8.3/anaconda3/lib/python3.6/site-packages/numpy/core/arrayprint.py", line 246, in set_printoptions
    floatmode, legacy)
  File "/usr/local/gfortran-8.3/anaconda3/lib/python3.6/site-packages/numpy/core/arrayprint.py", line 93, in _make_options_dict
    raise ValueError("threshold must be numeric and non-NAN, try "
ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

----------------------------------------------------------------------
Ran 87 tests in 92.490s

FAILED (SKIP=2, errors=1)

**Comment by bekozi** [comment]
Thanks for reporting @basmac. This appears to be an `icclim` error:
```
File "/usr/local/gfortran-8.3/anaconda3/lib/python3.6/site-packages/icclim/calc_percentiles.py", line 10, in 
numpy.set_printoptions(threshold=numpy.nan)
```
I'll post the issue on that site there and link to this issue. Unless you are using `icclim`, there should not be any issues.

**Comment by bekozi** [comment]
@basmac Has there been any recurring issues associated with this failure? I'd like to close the ticket if not. Thank you!

**Comment by pagecp** [comment]
It seems that a weird threshold value was used? I am also closing the issue in icclim as I cannot reproduce without more information.
